### ISSUE TITLE
error with "Unhandled error in deferred"

### ISSUE THREAD

**Issue by chaoshengt** [soaringsoul/easypoi#1]
@xugongli 出现这个错误。安装方式选择的是 pip install requirements.txt安装。 重新安装了pywin32 ，错误仍然有~~~
另：百度ak和高等ak已重新设置，mysql已设置~~~
@xugongli 求解，十分感谢！！

**Comment by soaringsoul** [comment]
抱歉，这个问题是因为一些依赖库没有安装完全。
我之前 没有测试，之前在requirements.txt写的依赖库没有写完全，目前已经测试并重新上传了。

步骤如下：
1.首先安装 `Twisted`
2.安装 pywin32
3.运行 pip install requirements.txt
4.python run.py

已经测试，可以正常运行了。
